divert(-1)
# This file is part of GNU RADIUS.
# Copyright (C) 2000,2001 Sergey Poznyakoff
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# $Id$
define([_SUITEDIR],[dejagnu])
define([_HEADER],[# This file is automatically generated. Please, do not edit
# Source: $1:$2])

dnl ***
dnl SEQUENCE(NAME,COMMENT,tests...)
define([SEQUENCE],[define([_SEQ_NUM],incr(_SEQ_NUM))
cat > FILENAME($1,3,exp) <<'EOF'
_HEADER(__file__,__line__)
clone_output "[$2]"
$3
EOF[]dnl])

dnl ***
dnl IFSEQUENCE(NAME,CAPA,COMMENT,tests...)
define([IFSEQUENCE],[define([_SEQ_NUM],incr(_SEQ_NUM))
cat > FILENAME($1,3,exp) <<'EOF'
_HEADER(__file__,__line__)
default_radiusd_version
if { [[info exists CAPABILITY($2)]] } {
   $4
} else {
   unsupported "$3"
}
EOF[]dnl])

dnl ***
define([QUOTE],[patsubst([$1],["],[\\"])])

dnl ***
dnl TEST(SEND,EXPECT,[PATTERN])
define([TEST],[radius_test "QUOTE([$1])" "QUOTE([$2])" ifelse($#,3,["QUOTE([$3])"])])

dnl ***
dnl DISPLAY(TEXT)
define([DISPLAY],[clone_output "$1"])
divert[]dnl
