divert(-1)
# This file is part of GNU RADIUS.
# Copyright (C) 2000,2001 Sergey Poznyakoff
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# $Id$
define([_SUITEDIR],[shell])

define([_HEADER],[# This file is automatically generated. Please, do not edit
# Source: $1:$2])

define([QUOTE],"[$1]")
define([DEREF],[$$1[[$2]]])
define([ESC],[ifelse($1,,,[$1[]ESC(shift($@))])])


dnl ***
define([BEGIN],[SEQUENCE(Start,,echo [$1])])

define([END],[SEQUENCE(Stop,,echo exit)])

dnl ***
dnl DISPLAY(TEXT)
define([DISPLAY],[ifelse(x[$1],x,,echo 'print "[[$1]]"')])

dnl ***
dnl SEQUENCE(NAME,COMMENT,tests...)
define([SEQUENCE],[define([_SEQ_NUM],incr(_SEQ_NUM))
cat > FILENAME($1,3,sh) <<'EOF'
_HEADER(__file__,__line__)
DISPLAY([$2])
$3
EOF[]dnl])

dnl ***
dnl IFSEQUENCE(NAME,CAPA,COMMENT,tests...)
define([IFSEQUENCE],[define([_SEQ_NUM],incr(_SEQ_NUM))
cat > FILENAME($1,3,sh) <<'EOF'
_HEADER(__file__,__line__)
if test "x$[$2]" = "x1"; then
   $4
else
   echo 'print "UNSUPPORTED"'
fi
EOF[]dnl])

define([_TEST_NUM],0)

dnl ***
dnl TEST(SEND,EXPECT,[PATTERN])
define([TEST],[define([_TEST_NUM],incr(_TEST_NUM))
echo 'print ":_TEST_NUM:ifelse($#,3,[$3]:)"'
echo '[$1]'
echo '[$2]'])
divert[]dnl
