#! /bin/sh

gnulibdir=${1:?}
shift

for dir in gnu build-aux
do
  if [ -d $dir ]; then :; else mkdir $dir || exit 1; fi
done  
   
if [ -x $gnulibdir/gnulib-tool -a -x $gnulibdir/build-aux/bootstrap ]; then
   $gnulibdir/build-aux/bootstrap --gnulib-srcdir=$gnulibdir $* || exit 1
   echo "$0: Configuring"
   ./configure --enable-maintainer-mode || exit 1
   echo "$0: Done. You may run make now"
else
   echo "usage: ./bootstrap GNULIB-DIR [options]"
   exit 1 
fi
