#! /bin/sh

dir=${1:?}
shift

if [ -d gnu ]; then :; else mkdir gnu || exit 1; fi
   
if [ -x $dir/gnulib-tool -a -x $dir/build-aux/bootstrap ]; then
   $dir/build-aux/bootstrap --gnulib-srcdir=$dir $* || exit 1
   echo "$0: Configuring"
   ./configure --enable-maintainer-mode || exit 1
   echo "$0: Done. You may run make now"
else
   echo "usage: ./bootstrap GNULIB-DIR [options]"
   exit 1 
fi
