@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Debugging, Extensions, Logging, Top
@chapter Debugging
@cindex Debugging

GNU Radius provides extensive debugging features. These are enabled
either by the @option{-x} command option to @command{radiusd}
@ref{Invocation}, or by the @code{level} statement in the debug category
(@ref{logging,,logging statement}). Both cases require as an argument
a valid debug specification.

A debug specification sets the module for which the debugging should
be enabled and the debugging level. The higher the level is, the more
detailed information is provided. The module name and level are
separated by an equal sign. If the level is omitted, the highest
possible level (100) is assumed. The module name may be abbreviated
to the first @math{N} characters, in which case the first matching module is
selected. Several such specifications can be specified, in which case
they should be separated by commas. For example, the following is a
valid debug specification:
@smallexample
        proxy.c=10,files.c,config.y=1
@end smallexample

@noindent
It sets debug level 10 for module @code{proxy.c}, 100 for
@code{files.c}, and 1 for @code{config.y}.

The modules and debugging levels are subject to change from release
to release. 

@c The following describes briefly the debugging levels for this release
@c of GNU Radius (@value{VERSION}).

@c @include debug.texinfo


