@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001,2002,2003 Free Software Foundation, Inc.
@c Written by Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radauth, Radctl, Radping, Utility Programs
@section @command{radauth}
@pindex radauth

The @command{radauth} utility sends the Radius server an Access-Request
packet and displays the result it gets. It can be used to test the
configuration files. The usage is

@smallexample
radauth [-v] username password
@end smallexample

The @option{-v} or @option{--verbose} option forces @command{radauth} to be
verbose on output.

If you enter @samp{.} (dot) instead of the password, the program
will disable echoing on the screen, prompt you to enter the password,
and turn the echoing on again, thus preventing the password from being
compromised.

The program determines which Radius server to use, the authentication
port number, and the shared secret, following the procedure common to all
client scripts (@pxref{config}).


