@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radctl, Builddbm, Radauth, Utility Programs
@section @command{radctl}
@pindex radctl

@command{Radctl} is a control interface to the @command{radiusd}
daemon. It allows the
user running it to query @command{radiusd} about various aspects of its
work and to issue administrative commands to it. The syntax is

@example
radctl -s @var{command} [@var{args}]
@end example

@noindent
where @var{command} is a command telling @command{radctl} which actions to
take, and @var{args} are optional arguments to the command. Only one
command can be specified per invocation.

The valid commands are as follows:

@table @code

@item start [@var{args}]
If @command{radiusd} is not running already, it is started. When
present, @var{args} are passed as the command line to the
server.

@item stop
Stops running @command{radiusd}.

@item restart [@var{args}]
Stops the server and then starts it again. When present, @var{args}
are passed as the command line to the server.

@item reload
Causes the running @command{radiusd} server to reread its configuration files.

@item dumpdb
Tells @command{radiusd} to dump its user hash table into the file
@file{@var{radlog}/radius.parse}. This can be used for debugging 
configuration files.

@item status
@command{radiusd} reports its memory usage statistics. The information is
logged at the @code{Info} log level.

@item which
Reports the the running version of @command{radiusd}.

@end table


