@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radctl, Builddbm, Radauth, Utility Programs
@section Radctl
@pindex radctl

@command{Radctl} is a control interface to @command{radiusd} daemon. It allows
user running it to query @command{radiusd} about various aspects of its
work and issue administrative commands to it. 

@example
radctl -s @var{command} [@var{args}]
@end example

Where @var{command} is a command telling @command{radctl} which actions to
take, and @var{args} are optional arguments to the command. Only one
command can be specified per invocation.

The valid @var{command}s are as follows:

@table @code

@item start [@var{args}]
If @command{radiusd} is not running already, it is started. When
present, @var{args} are passed as the command line to the
server.

@item stop
Stops running @command{radiusd}.

@item restart [@var{args}]
Stops the server and then starts it again. When present, @var{args}
are passed as the command line to the server.

@item reload
Causes running @command{radiusd} server to re-read its configuration files.

@item dumpdb
Tells @command{radiusd} to dump its user hash table into the file
@file{@value{RADLOG}/radius.parse}. This can be used for debugging 
configuration files.

@item status
@command{radiusd} reports its memory usage statistics. The information is
logged under @code{Info} log level.

@item which
Reports the information about the running copy of @command{radiusd}.

@end table


