@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radgrep, Radping, Radzap, Top
@chapter Radgrep
@pindex radgrep

This utility allows to quickly lookup the user in the radius accounting
database using a regular expression match.

@code{radgrep} scans the output of @code{radwho} utility and outputs
only the lines that match given @code{grep} regular expressions.

@subheading Syntax
@code{radgrep} accepts two sets of options separated by @samp{--}
(double-dash) sign. First subset is passed as command line to
@code{radwho} utility. The second one is passed to @code{grep}.

