@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radgrep, Radping, Radzap, Utility Programs
@section Radgrep
@pindex radgrep

This utility allows to quickly lookup the user in the radius accounting
database using a regular expression match.

@command{radgrep} scans the output of @command{radwho} utility and outputs
only the lines that match given regular expressions.

@subheading Syntax
@command{radgrep} accepts two sets of options separated by @samp{--}
(double-dash) sign. First subset is passed as command line to
@command{radwho} utility. The second one is passed to @command{grep}.

