@c This is part of the Radius manual.
@c Copyright (C) 1999,2000,2001 Sergey Poznyakoff
@c See file radius.texi for copying conditions.
@comment *******************************************************************
@node Radlast, Raduse, Radwho, Top
@chapter Radlast
@pindex radlast

The @code{radlast} utility lists sessions of specified users, NASes,
NAS ports and hosts, in reverse time order. By default, each line of output
contains the login name, NAS short name and port number from where the
session was conducted, host IP address or name, the start and stop
times for the session, and the duration of the session. If the session
is still continuing, @code{radlast} will so indicate.

When specified the @samp{-l} option, @code{radlast} produces long
output. It includes following fields:

@itemize @bullet
@item login name
@item NAS short name
@item port number
@item prototype
@item port type
@item Session ID
@item Caller ID
@item Framed IP address
@item Session Start Time
@item Session Stop Time
@item Duration of the Session
@end itemize


@menu
* Options: radlast options.      Command line options.
@end menu

@comment *******************************************************************
@node radlast options, , , Radlast
@chapter @code{radlast} command line options
@pindex @code{radlast}, options

Use following command line options to control the behavior of
@code{radlast} utility:

@table @samp
@item -@var{number}
@itemx -c @var{number}
@itemx --count @var{number}
When given this option @code{radlast} will output at most this many
lines of information. 

@item -f
@itemx --file @var{name}
Read the specified file instead of the default @file{/var/log/radwtmp}.

@item -h @var{hostname}
@itemx --host @var{hostname}
Report the logins from given host. Host can be either a name or a
"dotted quad" internet address.

@item -n @var{shortname}
@itemx --nas @var{shortname}
Report the logins from given Network Access Server (NAS).

@item -l
@itemx --long-format
"Long" output format. Report all the information stored in
@file{radwtmp} file.

@item -p @var{number}
@itemx --port @var{number}
Report the logins on a given port. The port may be specified either fully or
abbreviated, e.g. @code{radlast -p 3} or @code{radlast -p S03}.

@item -s
@itemx --show-seconds
Report the duration of the login session in seconds instead of the
default days, hours and minutes.

@item -t
The same as @samp{-p}. This flag is provided for compatibility with last(1).

@item -w
@itemx --wide
Widen the duration field to show seconds as well as the default days,
hours and minutes.

@end table

If multiple arguments are given, the logical OR operation between them
is assumed, i.e. the information selected by each argument
is printed. This, however, does not apply to @code{-c} option. This option is
always combined with the rest of command line by logical AND.

The pseudo-user ~reboot logs in on every reboot of network access
server.

If @code{radlast} is interrupted, it indicates to what date the search
was progressed.
