# -*- tcl -*-
# This file is part of GNU RADIUS test suite.
# Copyright (C) 2000,2001 Sergey Poznyakoff
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

clone_output "Checking accountng stop"

radius_test -message "Acct start" \
	    "acct 4 User-Name = \"simuse\" \
                    NAS-IP-Address = \"127.0.0.1\" \
                    NAS-Port-Id = 1 \
                    Acct-Session-Id = \"0001\" \
                    Acct-Status-Type = Stop" \
            "5"

# Fixme: Check details

clone_output "Checking Simultaneous-Use attribute"

radius_test -message "Simultaneous-Use pass" \
	    "auth 1 User-Name = \"simuse\"" \
	    "2 Service-Type = 2" 
