# -*- tcl -*-
# This file is part of GNU RADIUS test suite.
# Copyright (C) 2000,2001 Sergey Poznyakoff
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

clone_output "Checking Exec-Program-Wait attribute"

radius_test -message "Exec-Program-Wait acknowledge" \
	    "auth 1 User-Name = \"execwait\" NAS-Port-Id = 0" \
	    "2 Service-Type = 1 Reply-Message = \"Welcome, execwait\""
radius_test -message "Exec-Program-Wait reject" \
	    "auth 1 User-Name = \"execwait\" NAS-Port-Id = 1"  \
	    "3"

