# -*- tcl -*-
# This file is part of GNU RADIUS test suite.
# Copyright (C) 2000,2001 Sergey Poznyakoff
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

clone_output "Checking Reply Attributes"

radius_test -message "Reply Attributes" "auth 1 User-Name = \"reply\" Password = \"guessme\"" \
	      "2 Service-Type = 2 Framed-Protocol = 1"

radius_test -message "Framed IP + port-number" \
	    "auth 1 User-Name = \"framed-ip\" NAS-Port-Id = 10" \
	    "2 Service-Type = 2 Framed-Protocol = 1 Framed-IP-Address = \"127.0.0.11\""
