# -*- tcl -*-
# This file is part of GNU RADIUS test suite.
# Copyright (C) 2000,2001 Sergey Poznyakoff
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

clone_output "Checking rewrite rules"

radius_test "auth 1 User-Name = rewrite_max \
	            NAS-IP-Address = 127.0.0.5 \
		    NAS-Port-Id = 20212" \
            "2 Reply-Message = OK"		    

radius_test "auth 1 User-Name = \"WGROUP\\\\rewrite_nt\" \
	            NAS-IP-Address = 127.0.0.5 \
		    NAS-Port-Id = 2" \
            "2 Reply-Message = OK"		    

radius_test "auth 1 User-Name = \"rewrite_je/tstream\" \
	            NAS-IP-Address = 127.0.0.5 \
		    NAS-Port-Id = 3" \
            "2 Reply-Message = OK"		    

radius_test "auth 1 User-Name = \"rewrite_cisco\" \
	            NAS-IP-Address = 127.0.0.5 \
		    Cisco-PRI-Circuit = \"ISDN 2:D:123\" \
Acct-Session-Id = \"120104/18:02:06.020 EEST Thu Dec 7 2000/hostname/1B22539E 86E6603F 0 19C974C0/answer/Telephony////\"" \
            "2 Reply-Message = OK"		    
		    
