# -*- tcl -*-
# This file is part of GNU RADIUS test suite.
# Copyright (C) 2000,2001 Sergey Poznyakoff
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

set message "Stress test"

set count 2000
set success 0
set failed 0

clone_output "$message. Sending $count authentication requests."
clone_output "Please wait, this can take a while..."

for {set i 0} {$i < $count} {incr i} {
    set status [default_radius_test \
	               "auth 1 User-Name = \"accept\" \
		               NAS-IP-Address = 127.0.0.1 \
			       NAS-Port-Id = 1 \
			       NAS-Port-Type = Sync \
			       Called-Station-Id = \"99999999999\" \
                               Calling-Station-Id = \"11111111111\"" \
			       "2"]
    if {$status == 0} {
	incr success
    } else {
	incr failed
    }
}

if {$failed == 0 && $success == $count} {
    pass "$message"
} else {
    fail "$message ($failed out of $count)"
}

