/* $Id$ */
/* This file is automatically generated
 * Please, do not edit.
 * Source file: ../mibs/radmibs.h.in
 */
#define MIB_AuthServIdent 1,3,6,1,2,1,67,1,1,1,1,1
#define LEN_AuthServIdent 12
#define MIB_KEY_AuthServIdent 1
#define MIB_AuthServUpTime 1,3,6,1,2,1,67,1,1,1,1,2
#define LEN_AuthServUpTime 12
#define MIB_KEY_AuthServUpTime 2
#define MIB_AuthServResetTime 1,3,6,1,2,1,67,1,1,1,1,3
#define LEN_AuthServResetTime 12
#define MIB_KEY_AuthServResetTime 3
#define MIB_AuthServConfigReset 1,3,6,1,2,1,67,1,1,1,1,4
#define LEN_AuthServConfigReset 12
#define MIB_KEY_AuthServConfigReset 4
#define MIB_AuthServTotalAccessRequests 1,3,6,1,2,1,67,1,1,1,1,5
#define LEN_AuthServTotalAccessRequests 12
#define MIB_KEY_AuthServTotalAccessRequests 5
#define MIB_AuthServTotalInvalidRequests 1,3,6,1,2,1,67,1,1,1,1,6
#define LEN_AuthServTotalInvalidRequests 12
#define MIB_KEY_AuthServTotalInvalidRequests 6
#define MIB_AuthServTotalDupAccessRequests 1,3,6,1,2,1,67,1,1,1,1,7
#define LEN_AuthServTotalDupAccessRequests 12
#define MIB_KEY_AuthServTotalDupAccessRequests 7
#define MIB_AuthServTotalAccessAccepts 1,3,6,1,2,1,67,1,1,1,1,8
#define LEN_AuthServTotalAccessAccepts 12
#define MIB_KEY_AuthServTotalAccessAccepts 8
#define MIB_AuthServTotalAccessRejects 1,3,6,1,2,1,67,1,1,1,1,9
#define LEN_AuthServTotalAccessRejects 12
#define MIB_KEY_AuthServTotalAccessRejects 9
#define MIB_AuthServTotalAccessChallenges 1,3,6,1,2,1,67,1,1,1,1,10
#define LEN_AuthServTotalAccessChallenges 12
#define MIB_KEY_AuthServTotalAccessChallenges 10
#define MIB_AuthServTotalMalformedAccessRequests 1,3,6,1,2,1,67,1,1,1,1,11
#define LEN_AuthServTotalMalformedAccessRequests 12
#define MIB_KEY_AuthServTotalMalformedAccessRequests 11
#define MIB_AuthServTotalBadAuthenticators 1,3,6,1,2,1,67,1,1,1,1,12
#define LEN_AuthServTotalBadAuthenticators 12
#define MIB_KEY_AuthServTotalBadAuthenticators 12
#define MIB_AuthServTotalPacketsDropped 1,3,6,1,2,1,67,1,1,1,1,13
#define LEN_AuthServTotalPacketsDropped 12
#define MIB_KEY_AuthServTotalPacketsDropped 13
#define MIB_AuthServTotalUnknownTypes 1,3,6,1,2,1,67,1,1,1,1,14
#define LEN_AuthServTotalUnknownTypes 12
#define MIB_KEY_AuthServTotalUnknownTypes 14
#define MIB_AuthClientIndex 1,3,6,1,2,1,67,1,1,1,1,15,1,1,-1
#define LEN_AuthClientIndex 15
#define MIB_KEY_AuthClientIndex 1
#define MIB_AuthClientAddress 1,3,6,1,2,1,67,1,1,1,1,15,1,2,-1
#define LEN_AuthClientAddress 15
#define MIB_KEY_AuthClientAddress 2
#define MIB_AuthClientID 1,3,6,1,2,1,67,1,1,1,1,15,1,3,-1
#define LEN_AuthClientID 15
#define MIB_KEY_AuthClientID 3
#define MIB_AuthServAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,4,-1
#define LEN_AuthServAccessRequests 15
#define MIB_KEY_AuthServAccessRequests 4
#define MIB_AuthServDupAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,5,-1
#define LEN_AuthServDupAccessRequests 15
#define MIB_KEY_AuthServDupAccessRequests 5
#define MIB_AuthServAccessAccepts 1,3,6,1,2,1,67,1,1,1,1,15,1,6,-1
#define LEN_AuthServAccessAccepts 15
#define MIB_KEY_AuthServAccessAccepts 6
#define MIB_AuthServAccessRejects 1,3,6,1,2,1,67,1,1,1,1,15,1,7,-1
#define LEN_AuthServAccessRejects 15
#define MIB_KEY_AuthServAccessRejects 7
#define MIB_AuthServAccessChallenges 1,3,6,1,2,1,67,1,1,1,1,15,1,8,-1
#define LEN_AuthServAccessChallenges 15
#define MIB_KEY_AuthServAccessChallenges 8
#define MIB_AuthServMalformedAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,9,-1
#define LEN_AuthServMalformedAccessRequests 15
#define MIB_KEY_AuthServMalformedAccessRequests 9
#define MIB_AuthServBadAuthenticators 1,3,6,1,2,1,67,1,1,1,1,15,1,10,-1
#define LEN_AuthServBadAuthenticators 15
#define MIB_KEY_AuthServBadAuthenticators 10
#define MIB_AuthServPacketsDropped 1,3,6,1,2,1,67,1,1,1,1,15,1,11,-1
#define LEN_AuthServPacketsDropped 15
#define MIB_KEY_AuthServPacketsDropped 11
#define MIB_AuthServUnknownTypes 1,3,6,1,2,1,67,1,1,1,1,15,1,12,-1
#define LEN_AuthServUnknownTypes 15
#define MIB_KEY_AuthServUnknownTypes 12
#define MIB_AccServIdent 1,3,6,1,2,1,67,2,1,1,1,1
#define LEN_AccServIdent 12
#define MIB_KEY_AccServIdent 1
#define MIB_AccServUpTime 1,3,6,1,2,1,67,2,1,1,1,2
#define LEN_AccServUpTime 12
#define MIB_KEY_AccServUpTime 2
#define MIB_AccServResetTime 1,3,6,1,2,1,67,2,1,1,1,3
#define LEN_AccServResetTime 12
#define MIB_KEY_AccServResetTime 3
#define MIB_AccServConfigReset 1,3,6,1,2,1,67,2,1,1,1,4
#define LEN_AccServConfigReset 12
#define MIB_KEY_AccServConfigReset 4
#define MIB_AccServTotalRequests 1,3,6,1,2,1,67,2,1,1,1,5
#define LEN_AccServTotalRequests 12
#define MIB_KEY_AccServTotalRequests 5
#define MIB_AccServTotalInvalidRequests 1,3,6,1,2,1,67,2,1,1,1,6
#define LEN_AccServTotalInvalidRequests 12
#define MIB_KEY_AccServTotalInvalidRequests 6
#define MIB_AccServTotalDupRequests 1,3,6,1,2,1,67,2,1,1,1,7
#define LEN_AccServTotalDupRequests 12
#define MIB_KEY_AccServTotalDupRequests 7
#define MIB_AccServTotalResponses 1,3,6,1,2,1,67,2,1,1,1,8
#define LEN_AccServTotalResponses 12
#define MIB_KEY_AccServTotalResponses 8
#define MIB_AccServTotalMalformedRequests 1,3,6,1,2,1,67,2,1,1,1,9
#define LEN_AccServTotalMalformedRequests 12
#define MIB_KEY_AccServTotalMalformedRequests 9
#define MIB_AccServTotalBadAuthenticators 1,3,6,1,2,1,67,2,1,1,1,10
#define LEN_AccServTotalBadAuthenticators 12
#define MIB_KEY_AccServTotalBadAuthenticators 10
#define MIB_AccServTotalPacketsDropped 1,3,6,1,2,1,67,2,1,1,1,11
#define LEN_AccServTotalPacketsDropped 12
#define MIB_KEY_AccServTotalPacketsDropped 11
#define MIB_AccServTotalNoRecords 1,3,6,1,2,1,67,2,1,1,1,12
#define LEN_AccServTotalNoRecords 12
#define MIB_KEY_AccServTotalNoRecords 12
#define MIB_AccServTotalUnknownTypes 1,3,6,1,2,1,67,2,1,1,1,13
#define LEN_AccServTotalUnknownTypes 12
#define MIB_KEY_AccServTotalUnknownTypes 13
#define MIB_AccClientIndex 1,3,6,1,2,1,67,2,1,1,1,14,1,1,-1
#define LEN_AccClientIndex 15
#define MIB_KEY_AccClientIndex 1
#define MIB_AccClientAddress 1,3,6,1,2,1,67,2,1,1,1,14,1,2,-1
#define LEN_AccClientAddress 15
#define MIB_KEY_AccClientAddress 2
#define MIB_AccClientID 1,3,6,1,2,1,67,2,1,1,1,14,1,3,-1
#define LEN_AccClientID 15
#define MIB_KEY_AccClientID 3
#define MIB_AccServPacketsDropped 1,3,6,1,2,1,67,2,1,1,1,14,1,4,-1
#define LEN_AccServPacketsDropped 15
#define MIB_KEY_AccServPacketsDropped 4
#define MIB_AccServRequests 1,3,6,1,2,1,67,2,1,1,1,14,1,5,-1
#define LEN_AccServRequests 15
#define MIB_KEY_AccServRequests 5
#define MIB_AccServDupRequests 1,3,6,1,2,1,67,2,1,1,1,14,1,6,-1
#define LEN_AccServDupRequests 15
#define MIB_KEY_AccServDupRequests 6
#define MIB_AccServResponses 1,3,6,1,2,1,67,2,1,1,1,14,1,7,-1
#define LEN_AccServResponses 15
#define MIB_KEY_AccServResponses 7
#define MIB_AccServBadAuthenticators 1,3,6,1,2,1,67,2,1,1,1,14,1,8,-1
#define LEN_AccServBadAuthenticators 15
#define MIB_KEY_AccServBadAuthenticators 8
#define MIB_AccServMalformedRequests 1,3,6,1,2,1,67,2,1,1,1,14,1,9,-1
#define LEN_AccServMalformedRequests 15
#define MIB_KEY_AccServMalformedRequests 9
#define MIB_AccServNoRecords 1,3,6,1,2,1,67,2,1,1,1,14,1,10,-1
#define LEN_AccServNoRecords 15
#define MIB_KEY_AccServNoRecords 10
#define MIB_AccServUnknownTypes 1,3,6,1,2,1,67,2,1,1,1,14,1,11,-1
#define LEN_AccServUnknownTypes 15
#define MIB_KEY_AccServUnknownTypes 11
#define MIB_StatIdent 1,3,6,1,4,1,9163,3,1,1
#define LEN_StatIdent 10
#define MIB_KEY_StatIdent 1
#define MIB_StatUpTime 1,3,6,1,4,1,9163,3,1,2
#define LEN_StatUpTime 10
#define MIB_KEY_StatUpTime 2
#define MIB_StatConfigReset 1,3,6,1,4,1,9163,3,1,3
#define LEN_StatConfigReset 10
#define MIB_KEY_StatConfigReset 3
#define MIB_StatTotalLines 1,3,6,1,4,1,9163,3,1,4
#define LEN_StatTotalLines 10
#define MIB_KEY_StatTotalLines 4
#define MIB_StatTotalLinesInUse 1,3,6,1,4,1,9163,3,1,5
#define LEN_StatTotalLinesInUse 10
#define MIB_KEY_StatTotalLinesInUse 5
#define MIB_StatTotalLinesIdle 1,3,6,1,4,1,9163,3,1,6
#define LEN_StatTotalLinesIdle 10
#define MIB_KEY_StatTotalLinesIdle 6
#define MIB_NASIndex1 1,3,6,1,4,1,9163,3,1,7,1,1,-1
#define LEN_NASIndex1 13
#define MIB_KEY_NASIndex1 1
#define MIB_NASIndex2 1,3,6,1,4,1,9163,3,1,7,1,1,-1,-1
#define LEN_NASIndex2 14
#define MIB_KEY_NASIndex2 -1
#define MIB_NASIndex3 1,3,6,1,4,1,9163,3,1,7,1,1,-1,-1,-1
#define LEN_NASIndex3 15
#define MIB_KEY_NASIndex3 -1
#define MIB_NASIndex4 1,3,6,1,4,1,9163,3,1,7,1,1,-1,-1,-1,-1
#define LEN_NASIndex4 16
#define MIB_KEY_NASIndex4 -1
#define MIB_NASAddress 1,3,6,1,4,1,9163,3,1,7,1,2,-1
#define LEN_NASAddress 13
#define MIB_KEY_NASAddress 2
#define MIB_NASID 1,3,6,1,4,1,9163,3,1,7,1,3,-1
#define LEN_NASID 13
#define MIB_KEY_NASID 3
#define MIB_NASLines 1,3,6,1,4,1,9163,3,1,7,1,4,-1
#define LEN_NASLines 13
#define MIB_KEY_NASLines 4
#define MIB_NASLinesInUse 1,3,6,1,4,1,9163,3,1,7,1,5,-1
#define LEN_NASLinesInUse 13
#define MIB_KEY_NASLinesInUse 5
#define MIB_NASLinesIdle 1,3,6,1,4,1,9163,3,1,7,1,6,-1
#define LEN_NASLinesIdle 13
#define MIB_KEY_NASLinesIdle 6
#define MIB_StatPortIndex1 1,3,6,1,4,1,9163,3,1,8,1,1,-1
#define LEN_StatPortIndex1 13
#define MIB_KEY_StatPortIndex1 1
#define MIB_StatPortIndex2 1,3,6,1,4,1,9163,3,1,8,1,1,-1,-1
#define LEN_StatPortIndex2 14
#define MIB_KEY_StatPortIndex2 -1
#define MIB_StatNASIndex 1,3,6,1,4,1,9163,3,1,8,1,2,-1
#define LEN_StatNASIndex 13
#define MIB_KEY_StatNASIndex 2
#define MIB_StatPortID 1,3,6,1,4,1,9163,3,1,8,1,3,-1
#define LEN_StatPortID 13
#define MIB_KEY_StatPortID 3
#define MIB_StatPortFramedAddress 1,3,6,1,4,1,9163,3,1,8,1,4,-1
#define LEN_StatPortFramedAddress 13
#define MIB_KEY_StatPortFramedAddress 4
#define MIB_StatPortTotalLogins 1,3,6,1,4,1,9163,3,1,8,1,5,-1
#define LEN_StatPortTotalLogins 13
#define MIB_KEY_StatPortTotalLogins 5
#define MIB_StatPortStatus 1,3,6,1,4,1,9163,3,1,8,1,6,-1
#define LEN_StatPortStatus 13
#define MIB_KEY_StatPortStatus 6
#define MIB_StatPortStatusChangeTimestamp 1,3,6,1,4,1,9163,3,1,8,1,7,-1
#define LEN_StatPortStatusChangeTimestamp 13
#define MIB_KEY_StatPortStatusChangeTimestamp 7
#define MIB_StatPortUpTime 1,3,6,1,4,1,9163,3,1,8,1,8,-1
#define LEN_StatPortUpTime 13
#define MIB_KEY_StatPortUpTime 8
#define MIB_StatPortLastLoginName 1,3,6,1,4,1,9163,3,1,8,1,9,-1
#define LEN_StatPortLastLoginName 13
#define MIB_KEY_StatPortLastLoginName 9
#define MIB_StatPortLastLoginTimestamp 1,3,6,1,4,1,9163,3,1,8,1,10,-1
#define LEN_StatPortLastLoginTimestamp 13
#define MIB_KEY_StatPortLastLoginTimestamp 10
#define MIB_StatPortLastLogoutTimestamp 1,3,6,1,4,1,9163,3,1,8,1,11,-1
#define LEN_StatPortLastLogoutTimestamp 13
#define MIB_KEY_StatPortLastLogoutTimestamp 11
#define MIB_StatPortIdleTotalTime 1,3,6,1,4,1,9163,3,1,8,1,12,-1
#define LEN_StatPortIdleTotalTime 13
#define MIB_KEY_StatPortIdleTotalTime 12
#define MIB_StatPortIdleMaxTime 1,3,6,1,4,1,9163,3,1,8,1,13,-1
#define LEN_StatPortIdleMaxTime 13
#define MIB_KEY_StatPortIdleMaxTime 13
#define MIB_StatPortIdleMaxTimestamp 1,3,6,1,4,1,9163,3,1,8,1,14,-1
#define LEN_StatPortIdleMaxTimestamp 13
#define MIB_KEY_StatPortIdleMaxTimestamp 14
#define MIB_StatPortInUseTotalTime 1,3,6,1,4,1,9163,3,1,8,1,15,-1
#define LEN_StatPortInUseTotalTime 13
#define MIB_KEY_StatPortInUseTotalTime 15
#define MIB_StatPortInUseMaxTime 1,3,6,1,4,1,9163,3,1,8,1,16,-1
#define LEN_StatPortInUseMaxTime 13
#define MIB_KEY_StatPortInUseMaxTime 16
#define MIB_StatPortInUseMaxTimestamp 1,3,6,1,4,1,9163,3,1,8,1,17,-1
#define LEN_StatPortInUseMaxTimestamp 13
#define MIB_KEY_StatPortInUseMaxTimestamp 17

#ifdef SERVER
subid_t oid_AuthServIdent[] = { LEN_AuthServIdent, MIB_AuthServIdent };
subid_t oid_AuthServUpTime[] = { LEN_AuthServUpTime, MIB_AuthServUpTime };
subid_t oid_AuthServResetTime[] = { LEN_AuthServResetTime, MIB_AuthServResetTime };
subid_t oid_AuthServConfigReset[] = { LEN_AuthServConfigReset, MIB_AuthServConfigReset };
subid_t oid_AuthServTotalAccessRequests[] = { LEN_AuthServTotalAccessRequests, MIB_AuthServTotalAccessRequests };
subid_t oid_AuthServTotalInvalidRequests[] = { LEN_AuthServTotalInvalidRequests, MIB_AuthServTotalInvalidRequests };
subid_t oid_AuthServTotalDupAccessRequests[] = { LEN_AuthServTotalDupAccessRequests, MIB_AuthServTotalDupAccessRequests };
subid_t oid_AuthServTotalAccessAccepts[] = { LEN_AuthServTotalAccessAccepts, MIB_AuthServTotalAccessAccepts };
subid_t oid_AuthServTotalAccessRejects[] = { LEN_AuthServTotalAccessRejects, MIB_AuthServTotalAccessRejects };
subid_t oid_AuthServTotalAccessChallenges[] = { LEN_AuthServTotalAccessChallenges, MIB_AuthServTotalAccessChallenges };
subid_t oid_AuthServTotalMalformedAccessRequests[] = { LEN_AuthServTotalMalformedAccessRequests, MIB_AuthServTotalMalformedAccessRequests };
subid_t oid_AuthServTotalBadAuthenticators[] = { LEN_AuthServTotalBadAuthenticators, MIB_AuthServTotalBadAuthenticators };
subid_t oid_AuthServTotalPacketsDropped[] = { LEN_AuthServTotalPacketsDropped, MIB_AuthServTotalPacketsDropped };
subid_t oid_AuthServTotalUnknownTypes[] = { LEN_AuthServTotalUnknownTypes, MIB_AuthServTotalUnknownTypes };
subid_t oid_AuthClientIndex[] = { LEN_AuthClientIndex, MIB_AuthClientIndex };
subid_t oid_AuthClientAddress[] = { LEN_AuthClientAddress, MIB_AuthClientAddress };
subid_t oid_AuthClientID[] = { LEN_AuthClientID, MIB_AuthClientID };
subid_t oid_AuthServAccessRequests[] = { LEN_AuthServAccessRequests, MIB_AuthServAccessRequests };
subid_t oid_AuthServDupAccessRequests[] = { LEN_AuthServDupAccessRequests, MIB_AuthServDupAccessRequests };
subid_t oid_AuthServAccessAccepts[] = { LEN_AuthServAccessAccepts, MIB_AuthServAccessAccepts };
subid_t oid_AuthServAccessRejects[] = { LEN_AuthServAccessRejects, MIB_AuthServAccessRejects };
subid_t oid_AuthServAccessChallenges[] = { LEN_AuthServAccessChallenges, MIB_AuthServAccessChallenges };
subid_t oid_AuthServMalformedAccessRequests[] = { LEN_AuthServMalformedAccessRequests, MIB_AuthServMalformedAccessRequests };
subid_t oid_AuthServBadAuthenticators[] = { LEN_AuthServBadAuthenticators, MIB_AuthServBadAuthenticators };
subid_t oid_AuthServPacketsDropped[] = { LEN_AuthServPacketsDropped, MIB_AuthServPacketsDropped };
subid_t oid_AuthServUnknownTypes[] = { LEN_AuthServUnknownTypes, MIB_AuthServUnknownTypes };
subid_t oid_AccServIdent[] = { LEN_AccServIdent, MIB_AccServIdent };
subid_t oid_AccServUpTime[] = { LEN_AccServUpTime, MIB_AccServUpTime };
subid_t oid_AccServResetTime[] = { LEN_AccServResetTime, MIB_AccServResetTime };
subid_t oid_AccServConfigReset[] = { LEN_AccServConfigReset, MIB_AccServConfigReset };
subid_t oid_AccServTotalRequests[] = { LEN_AccServTotalRequests, MIB_AccServTotalRequests };
subid_t oid_AccServTotalInvalidRequests[] = { LEN_AccServTotalInvalidRequests, MIB_AccServTotalInvalidRequests };
subid_t oid_AccServTotalDupRequests[] = { LEN_AccServTotalDupRequests, MIB_AccServTotalDupRequests };
subid_t oid_AccServTotalResponses[] = { LEN_AccServTotalResponses, MIB_AccServTotalResponses };
subid_t oid_AccServTotalMalformedRequests[] = { LEN_AccServTotalMalformedRequests, MIB_AccServTotalMalformedRequests };
subid_t oid_AccServTotalBadAuthenticators[] = { LEN_AccServTotalBadAuthenticators, MIB_AccServTotalBadAuthenticators };
subid_t oid_AccServTotalPacketsDropped[] = { LEN_AccServTotalPacketsDropped, MIB_AccServTotalPacketsDropped };
subid_t oid_AccServTotalNoRecords[] = { LEN_AccServTotalNoRecords, MIB_AccServTotalNoRecords };
subid_t oid_AccServTotalUnknownTypes[] = { LEN_AccServTotalUnknownTypes, MIB_AccServTotalUnknownTypes };
subid_t oid_AccClientIndex[] = { LEN_AccClientIndex, MIB_AccClientIndex };
subid_t oid_AccClientAddress[] = { LEN_AccClientAddress, MIB_AccClientAddress };
subid_t oid_AccClientID[] = { LEN_AccClientID, MIB_AccClientID };
subid_t oid_AccServPacketsDropped[] = { LEN_AccServPacketsDropped, MIB_AccServPacketsDropped };
subid_t oid_AccServRequests[] = { LEN_AccServRequests, MIB_AccServRequests };
subid_t oid_AccServDupRequests[] = { LEN_AccServDupRequests, MIB_AccServDupRequests };
subid_t oid_AccServResponses[] = { LEN_AccServResponses, MIB_AccServResponses };
subid_t oid_AccServBadAuthenticators[] = { LEN_AccServBadAuthenticators, MIB_AccServBadAuthenticators };
subid_t oid_AccServMalformedRequests[] = { LEN_AccServMalformedRequests, MIB_AccServMalformedRequests };
subid_t oid_AccServNoRecords[] = { LEN_AccServNoRecords, MIB_AccServNoRecords };
subid_t oid_AccServUnknownTypes[] = { LEN_AccServUnknownTypes, MIB_AccServUnknownTypes };
subid_t oid_StatIdent[] = { LEN_StatIdent, MIB_StatIdent };
subid_t oid_StatUpTime[] = { LEN_StatUpTime, MIB_StatUpTime };
subid_t oid_StatConfigReset[] = { LEN_StatConfigReset, MIB_StatConfigReset };
subid_t oid_StatTotalLines[] = { LEN_StatTotalLines, MIB_StatTotalLines };
subid_t oid_StatTotalLinesInUse[] = { LEN_StatTotalLinesInUse, MIB_StatTotalLinesInUse };
subid_t oid_StatTotalLinesIdle[] = { LEN_StatTotalLinesIdle, MIB_StatTotalLinesIdle };
subid_t oid_NASIndex1[] = { LEN_NASIndex1, MIB_NASIndex1 };
subid_t oid_NASIndex2[] = { LEN_NASIndex2, MIB_NASIndex2 };
subid_t oid_NASIndex3[] = { LEN_NASIndex3, MIB_NASIndex3 };
subid_t oid_NASIndex4[] = { LEN_NASIndex4, MIB_NASIndex4 };
subid_t oid_NASAddress[] = { LEN_NASAddress, MIB_NASAddress };
subid_t oid_NASID[] = { LEN_NASID, MIB_NASID };
subid_t oid_NASLines[] = { LEN_NASLines, MIB_NASLines };
subid_t oid_NASLinesInUse[] = { LEN_NASLinesInUse, MIB_NASLinesInUse };
subid_t oid_NASLinesIdle[] = { LEN_NASLinesIdle, MIB_NASLinesIdle };
subid_t oid_StatPortIndex1[] = { LEN_StatPortIndex1, MIB_StatPortIndex1 };
subid_t oid_StatPortIndex2[] = { LEN_StatPortIndex2, MIB_StatPortIndex2 };
subid_t oid_StatNASIndex[] = { LEN_StatNASIndex, MIB_StatNASIndex };
subid_t oid_StatPortID[] = { LEN_StatPortID, MIB_StatPortID };
subid_t oid_StatPortFramedAddress[] = { LEN_StatPortFramedAddress, MIB_StatPortFramedAddress };
subid_t oid_StatPortTotalLogins[] = { LEN_StatPortTotalLogins, MIB_StatPortTotalLogins };
subid_t oid_StatPortStatus[] = { LEN_StatPortStatus, MIB_StatPortStatus };
subid_t oid_StatPortStatusChangeTimestamp[] = { LEN_StatPortStatusChangeTimestamp, MIB_StatPortStatusChangeTimestamp };
subid_t oid_StatPortUpTime[] = { LEN_StatPortUpTime, MIB_StatPortUpTime };
subid_t oid_StatPortLastLoginName[] = { LEN_StatPortLastLoginName, MIB_StatPortLastLoginName };
subid_t oid_StatPortLastLoginTimestamp[] = { LEN_StatPortLastLoginTimestamp, MIB_StatPortLastLoginTimestamp };
subid_t oid_StatPortLastLogoutTimestamp[] = { LEN_StatPortLastLogoutTimestamp, MIB_StatPortLastLogoutTimestamp };
subid_t oid_StatPortIdleTotalTime[] = { LEN_StatPortIdleTotalTime, MIB_StatPortIdleTotalTime };
subid_t oid_StatPortIdleMaxTime[] = { LEN_StatPortIdleMaxTime, MIB_StatPortIdleMaxTime };
subid_t oid_StatPortIdleMaxTimestamp[] = { LEN_StatPortIdleMaxTimestamp, MIB_StatPortIdleMaxTimestamp };
subid_t oid_StatPortInUseTotalTime[] = { LEN_StatPortInUseTotalTime, MIB_StatPortInUseTotalTime };
subid_t oid_StatPortInUseMaxTime[] = { LEN_StatPortInUseMaxTime, MIB_StatPortInUseMaxTime };
subid_t oid_StatPortInUseMaxTimestamp[] = { LEN_StatPortInUseMaxTimestamp, MIB_StatPortInUseMaxTimestamp };
#endif
