/* $Id$ */
/* This file is automatically generated
 * Please, do not edit.
 * Source file: ../mibs/radmibs.h.in
 */
#define MIB_AuthServIdent 1,3,6,1,2,1,67,1,1,1,1,1
#define LEN_AuthServIdent 12
#define MIB_KEY_AuthServIdent 1
#define MIB_AuthServUpTime 1,3,6,1,2,1,67,1,1,1,1,2
#define LEN_AuthServUpTime 12
#define MIB_KEY_AuthServUpTime 2
#define MIB_AuthServResetTime 1,3,6,1,2,1,67,1,1,1,1,3
#define LEN_AuthServResetTime 12
#define MIB_KEY_AuthServResetTime 3
#define MIB_AuthServConfigReset 1,3,6,1,2,1,67,1,1,1,1,4
#define LEN_AuthServConfigReset 12
#define MIB_KEY_AuthServConfigReset 4
#define MIB_AuthServTotalAccessRequests 1,3,6,1,2,1,67,1,1,1,1,5
#define LEN_AuthServTotalAccessRequests 12
#define MIB_KEY_AuthServTotalAccessRequests 5
#define MIB_AuthServTotalInvalidRequests 1,3,6,1,2,1,67,1,1,1,1,6
#define LEN_AuthServTotalInvalidRequests 12
#define MIB_KEY_AuthServTotalInvalidRequests 6
#define MIB_AuthServTotalDupAccessRequests 1,3,6,1,2,1,67,1,1,1,1,7
#define LEN_AuthServTotalDupAccessRequests 12
#define MIB_KEY_AuthServTotalDupAccessRequests 7
#define MIB_AuthServTotalAccessAccepts 1,3,6,1,2,1,67,1,1,1,1,8
#define LEN_AuthServTotalAccessAccepts 12
#define MIB_KEY_AuthServTotalAccessAccepts 8
#define MIB_AuthServTotalAccessRejects 1,3,6,1,2,1,67,1,1,1,1,9
#define LEN_AuthServTotalAccessRejects 12
#define MIB_KEY_AuthServTotalAccessRejects 9
#define MIB_AuthServTotalAccessChallenges 1,3,6,1,2,1,67,1,1,1,1,10
#define LEN_AuthServTotalAccessChallenges 12
#define MIB_KEY_AuthServTotalAccessChallenges 10
#define MIB_AuthServTotalMalformedAccessRequests 1,3,6,1,2,1,67,1,1,1,1,11
#define LEN_AuthServTotalMalformedAccessRequests 12
#define MIB_KEY_AuthServTotalMalformedAccessRequests 11
#define MIB_AuthServTotalBadAuthenticators 1,3,6,1,2,1,67,1,1,1,1,12
#define LEN_AuthServTotalBadAuthenticators 12
#define MIB_KEY_AuthServTotalBadAuthenticators 12
#define MIB_AuthServTotalPacketsDropped 1,3,6,1,2,1,67,1,1,1,1,13
#define LEN_AuthServTotalPacketsDropped 12
#define MIB_KEY_AuthServTotalPacketsDropped 13
#define MIB_AuthServTotalUnknownTypes 1,3,6,1,2,1,67,1,1,1,1,14
#define LEN_AuthServTotalUnknownTypes 12
#define MIB_KEY_AuthServTotalUnknownTypes 14
#define MIB_AuthClientIndex 1,3,6,1,2,1,67,1,1,1,1,15,1,1,-1
#define LEN_AuthClientIndex 15
#define MIB_KEY_AuthClientIndex 1
#define MIB_AuthClientAddress 1,3,6,1,2,1,67,1,1,1,1,15,1,2,-1
#define LEN_AuthClientAddress 15
#define MIB_KEY_AuthClientAddress 2
#define MIB_AuthClientID 1,3,6,1,2,1,67,1,1,1,1,15,1,3,-1
#define LEN_AuthClientID 15
#define MIB_KEY_AuthClientID 3
#define MIB_AuthServAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,4,-1
#define LEN_AuthServAccessRequests 15
#define MIB_KEY_AuthServAccessRequests 4
#define MIB_AuthServDupAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,5,-1
#define LEN_AuthServDupAccessRequests 15
#define MIB_KEY_AuthServDupAccessRequests 5
#define MIB_AuthServAccessAccepts 1,3,6,1,2,1,67,1,1,1,1,15,1,6,-1
#define LEN_AuthServAccessAccepts 15
#define MIB_KEY_AuthServAccessAccepts 6
#define MIB_AuthServAccessRejects 1,3,6,1,2,1,67,1,1,1,1,15,1,7,-1
#define LEN_AuthServAccessRejects 15
#define MIB_KEY_AuthServAccessRejects 7
#define MIB_AuthServAccessChallenges 1,3,6,1,2,1,67,1,1,1,1,15,1,8,-1
#define LEN_AuthServAccessChallenges 15
#define MIB_KEY_AuthServAccessChallenges 8
#define MIB_AuthServMalformedAccessRequests 1,3,6,1,2,1,67,1,1,1,1,15,1,9,-1
#define LEN_AuthServMalformedAccessRequests 15
#define MIB_KEY_AuthServMalformedAccessRequests 9
#define MIB_AuthServBadAuthenticators 1,3,6,1,2,1,67,1,1,1,1,15,1,10,-1
#define LEN_AuthServBadAuthenticators 15
#define MIB_KEY_AuthServBadAuthenticators 10
#define MIB_AuthServPacketsDropped 1,3,6,1,2,1,67,1,1,1,1,15,1,11,-1
#define LEN_AuthServPacketsDropped 15
#define MIB_KEY_AuthServPacketsDropped 11
#define MIB_AuthServUnknownTypes 1,3,6,1,2,1,67,1,1,1,1,15,1,12,-1
#define LEN_AuthServUnknownTypes 15
#define MIB_KEY_AuthServUnknownTypes 12

#ifdef SERVER
subid_t oid_AuthServIdent[] = { LEN_AuthServIdent, MIB_AuthServIdent };
subid_t oid_AuthServUpTime[] = { LEN_AuthServUpTime, MIB_AuthServUpTime };
subid_t oid_AuthServResetTime[] = { LEN_AuthServResetTime, MIB_AuthServResetTime };
subid_t oid_AuthServConfigReset[] = { LEN_AuthServConfigReset, MIB_AuthServConfigReset };
subid_t oid_AuthServTotalAccessRequests[] = { LEN_AuthServTotalAccessRequests, MIB_AuthServTotalAccessRequests };
subid_t oid_AuthServTotalInvalidRequests[] = { LEN_AuthServTotalInvalidRequests, MIB_AuthServTotalInvalidRequests };
subid_t oid_AuthServTotalDupAccessRequests[] = { LEN_AuthServTotalDupAccessRequests, MIB_AuthServTotalDupAccessRequests };
subid_t oid_AuthServTotalAccessAccepts[] = { LEN_AuthServTotalAccessAccepts, MIB_AuthServTotalAccessAccepts };
subid_t oid_AuthServTotalAccessRejects[] = { LEN_AuthServTotalAccessRejects, MIB_AuthServTotalAccessRejects };
subid_t oid_AuthServTotalAccessChallenges[] = { LEN_AuthServTotalAccessChallenges, MIB_AuthServTotalAccessChallenges };
subid_t oid_AuthServTotalMalformedAccessRequests[] = { LEN_AuthServTotalMalformedAccessRequests, MIB_AuthServTotalMalformedAccessRequests };
subid_t oid_AuthServTotalBadAuthenticators[] = { LEN_AuthServTotalBadAuthenticators, MIB_AuthServTotalBadAuthenticators };
subid_t oid_AuthServTotalPacketsDropped[] = { LEN_AuthServTotalPacketsDropped, MIB_AuthServTotalPacketsDropped };
subid_t oid_AuthServTotalUnknownTypes[] = { LEN_AuthServTotalUnknownTypes, MIB_AuthServTotalUnknownTypes };
subid_t oid_AuthClientIndex[] = { LEN_AuthClientIndex, MIB_AuthClientIndex };
subid_t oid_AuthClientAddress[] = { LEN_AuthClientAddress, MIB_AuthClientAddress };
subid_t oid_AuthClientID[] = { LEN_AuthClientID, MIB_AuthClientID };
subid_t oid_AuthServAccessRequests[] = { LEN_AuthServAccessRequests, MIB_AuthServAccessRequests };
subid_t oid_AuthServDupAccessRequests[] = { LEN_AuthServDupAccessRequests, MIB_AuthServDupAccessRequests };
subid_t oid_AuthServAccessAccepts[] = { LEN_AuthServAccessAccepts, MIB_AuthServAccessAccepts };
subid_t oid_AuthServAccessRejects[] = { LEN_AuthServAccessRejects, MIB_AuthServAccessRejects };
subid_t oid_AuthServAccessChallenges[] = { LEN_AuthServAccessChallenges, MIB_AuthServAccessChallenges };
subid_t oid_AuthServMalformedAccessRequests[] = { LEN_AuthServMalformedAccessRequests, MIB_AuthServMalformedAccessRequests };
subid_t oid_AuthServBadAuthenticators[] = { LEN_AuthServBadAuthenticators, MIB_AuthServBadAuthenticators };
subid_t oid_AuthServPacketsDropped[] = { LEN_AuthServPacketsDropped, MIB_AuthServPacketsDropped };
subid_t oid_AuthServUnknownTypes[] = { LEN_AuthServUnknownTypes, MIB_AuthServUnknownTypes };
#endif
