divert(-1)
# This file is part of GNU RADIUS.
# Copyright (C) 2000,2001 Sergey Poznyakoff
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
# $Id$
define([_SUITEDIR],[dejagnu])
define([_HEADER],[# This file is automatically generated. Please, do not edit
# Source: $1:$2])

define([QUOTE],\"[$1]\")
define([DEREF],[\$$1\[[$2\]]])
define([ESC],[ifelse($1,,,[\$1[]ESC(shift($@))])])

dnl ***
define([BEGIN],[SEQUENCE(Start,,default_radiusd_start $1)])

define([END],[SEQUENCE(Stop,,radius_exit)
])

dnl ***
dnl _BEGIN_SEQUENCE(name, comment)
define([_BEGIN_SEQUENCE],[define([_SEQ_NUM],incr(_SEQ_NUM))
cat > FILENAME($1,3,exp) <<'EOF'
_HEADER(__file__,__line__)
clone_output "[$2]"])

dnl ***
dnl _END_SEQUENCE
define([_END_SEQUENCE],[EOF[]dnl])

dnl ***
dnl SEQUENCE(NAME,COMMENT,tests...)
define([SEQUENCE],[_BEGIN_SEQUENCE($1,$2)
$3
_END_SEQUENCE])

dnl ***
dnl IFSEQUENCE(NAME,CAPA,COMMENT,tests...)
define([IFSEQUENCE],[_BEGIN_SEQUENCE($1,$3)
default_radiusd_version
if { [[info exists CAPABILITY($2)]] } {
   $4
} else {
   unsupported "$3"
}
_END_SEQUENCE])

dnl ***
dnl TEST(SEND,EXPECT,[PATTERN])
define([TEST],[radius_test "[$1]" "[$2]" ifelse($#,3,["[$3]"])])

dnl ***
dnl DISPLAY(TEXT)
define([DISPLAY],[ifelse(x[$1],x,,clone_output "[[$1]]")])
divert[]dnl
